spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Taipei
    username: root
    password: 123456
  jpa:
    show-sql: true
jpa:
  hibernate:
    ddl-auto: create

logging:
  level:
    root: warn
    com.ryan: info
  file:
    path: log/blog-pro.log
server:
  port: 8081
